"""
PDF rendering and email delivery for ClearPath clearance letters.

The PDF renderer wraps the letter's HTML body in a clinical-letter template
with letterhead, recipient/sender block, subject line, and a footer disclaimer
that the letter is a draft for clinician review. PDFs are generated on demand
from the persisted letter — no PDF is stored at rest.

The email sender supports two backends:
  - SMTP via stdlib smtplib (configured via env vars)
  - "captured" fallback that just logs the would-be send (default when no
    SMTP config is present, so the demo never crashes for missing credentials)
"""

from __future__ import annotations

import io
import os
import smtplib
import ssl
from dataclasses import dataclass
from datetime import datetime, timezone
from email.message import EmailMessage
from typing import Any

from xhtml2pdf import pisa


_LETTERHEAD = {
    "facility_name": os.environ.get("CLEARPATH_FACILITY_NAME", "ClearPath Surgical Office"),
    "facility_address": os.environ.get("CLEARPATH_FACILITY_ADDRESS", "[Facility Address]"),
    "facility_phone": os.environ.get("CLEARPATH_FACILITY_PHONE", "[Phone]"),
    "facility_fax": os.environ.get("CLEARPATH_FACILITY_FAX", "[Fax]"),
}

_PDF_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  @page {{ size: letter; margin: 0.85in 0.85in 1in 0.85in; }}
  body {{
    font-family: Helvetica, Arial, sans-serif;
    font-size: 10.5pt;
    color: #1a1a1a;
    line-height: 1.45;
  }}
  .letterhead {{
    border-bottom: 1.5pt solid #333;
    padding-bottom: 8pt;
    margin-bottom: 18pt;
  }}
  .letterhead .facility-name {{
    font-size: 14pt;
    font-weight: bold;
    color: #0a4d3a;
    margin-bottom: 2pt;
  }}
  .letterhead .facility-detail {{
    font-size: 9pt;
    color: #555;
    margin: 0;
  }}
  .meta {{
    margin-bottom: 18pt;
    font-size: 9.5pt;
  }}
  .meta .row {{
    margin-bottom: 3pt;
  }}
  .meta .label {{
    color: #555;
    display: inline-block;
    width: 50pt;
  }}
  .meta .value {{
    color: #1a1a1a;
    font-weight: 600;
  }}
  .subject {{
    margin-top: 6pt;
    padding-top: 8pt;
    padding-bottom: 8pt;
    border-top: 0.5pt solid #ccc;
    border-bottom: 0.5pt solid #ccc;
    font-weight: 600;
  }}
  .body {{
    margin-top: 14pt;
  }}
  .body p {{ margin: 8pt 0; }}
  .body ul, .body ol {{ margin: 8pt 0 8pt 20pt; padding: 0; }}
  .body li {{ margin: 2pt 0; }}
  .body strong {{ font-weight: 700; }}
  .body em {{ font-style: italic; }}
  .body h2 {{ font-size: 11pt; margin: 14pt 0 4pt 0; }}
  .body h3 {{ font-size: 10.5pt; margin: 12pt 0 4pt 0; }}
  .footer {{
    margin-top: 32pt;
    padding-top: 8pt;
    border-top: 0.5pt solid #ccc;
    font-size: 8pt;
    color: #888;
    font-style: italic;
  }}
</style>
</head>
<body>
  <div class="letterhead">
    <div class="facility-name">{facility_name}</div>
    <div class="facility-detail">{facility_address}</div>
    <div class="facility-detail">Tel: {facility_phone} &nbsp;·&nbsp; Fax: {facility_fax}</div>
  </div>

  <div class="meta">
    <div class="row"><span class="label">Date:</span><span class="value">{date}</span></div>
    <div class="row"><span class="label">To:</span><span class="value">{to}</span></div>
    <div class="row"><span class="label">From:</span><span class="value">{from_}</span></div>
    <div class="subject">RE: {subject}</div>
  </div>

  <div class="body">{body_html}</div>

  <div class="footer">
    Draft for clinician review. Generated by ClearPath on {generated_at}. Not signed medical correspondence.
  </div>
</body>
</html>"""


@dataclass
class LetterMeta:
    to: str
    sender: str
    subject: str
    date: str | None = None


def render_letter_pdf(meta: LetterMeta, body_html: str) -> bytes:
    """Render a letter to PDF bytes using xhtml2pdf."""
    now = datetime.now(timezone.utc)
    date_str = meta.date or now.strftime("%B %d, %Y")
    html = _PDF_TEMPLATE.format(
        facility_name=_html_escape(_LETTERHEAD["facility_name"]),
        facility_address=_html_escape(_LETTERHEAD["facility_address"]),
        facility_phone=_html_escape(_LETTERHEAD["facility_phone"]),
        facility_fax=_html_escape(_LETTERHEAD["facility_fax"]),
        date=_html_escape(date_str),
        to=_html_escape(meta.to),
        from_=_html_escape(meta.sender),
        subject=_html_escape(meta.subject),
        body_html=body_html or "<p><em>(empty letter body)</em></p>",
        generated_at=_html_escape(now.strftime("%Y-%m-%d %H:%M UTC")),
    )

    buf = io.BytesIO()
    result = pisa.CreatePDF(src=html, dest=buf)
    if result.err:
        raise RuntimeError(f"PDF rendering failed: {result.err}")
    return buf.getvalue()


def _html_escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


# --- Email delivery ---------------------------------------------------------


@dataclass
class EmailDeliveryResult:
    sent: bool
    via: str
    detail: str | None = None


def send_letter_email(
    *,
    to_email: str,
    to_name: str | None,
    subject: str,
    body_text: str,
    pdf_bytes: bytes,
    pdf_filename: str,
) -> EmailDeliveryResult:
    """Send the letter PDF as an email attachment.

    Configuration via env vars:
      CLEARPATH_SMTP_HOST, CLEARPATH_SMTP_PORT (default 587),
      CLEARPATH_SMTP_USER, CLEARPATH_SMTP_PASS, CLEARPATH_FROM_EMAIL.

    When SMTP isn't configured, the call records a "captured" delivery — the
    UI shows the user the message would have gone out, no exception. This
    keeps the demo running without credentials while still letting prod
    deployments turn on real sending with three env vars.
    """
    host = os.environ.get("CLEARPATH_SMTP_HOST")
    user = os.environ.get("CLEARPATH_SMTP_USER")
    password = os.environ.get("CLEARPATH_SMTP_PASS")
    from_email = os.environ.get("CLEARPATH_FROM_EMAIL")
    port = int(os.environ.get("CLEARPATH_SMTP_PORT", "587"))

    if not (host and user and password and from_email):
        return EmailDeliveryResult(
            sent=False,
            via="captured",
            detail=(
                "SMTP is not configured (CLEARPATH_SMTP_HOST / CLEARPATH_SMTP_USER / "
                "CLEARPATH_SMTP_PASS / CLEARPATH_FROM_EMAIL). The PDF was generated but "
                "no email was transmitted. Configure these env vars to enable real sending."
            ),
        )

    msg = EmailMessage()
    msg["From"] = from_email
    msg["To"] = f"{to_name} <{to_email}>" if to_name else to_email
    msg["Subject"] = subject
    msg.set_content(body_text or "Please see the attached PDF for the clearance letter.")
    msg.add_attachment(
        pdf_bytes,
        maintype="application",
        subtype="pdf",
        filename=pdf_filename,
    )

    try:
        context = ssl.create_default_context()
        with smtplib.SMTP(host, port, timeout=30) as smtp:
            smtp.ehlo()
            smtp.starttls(context=context)
            smtp.ehlo()
            smtp.login(user, password)
            smtp.send_message(msg)
        return EmailDeliveryResult(sent=True, via="smtp", detail=f"Sent via {host}:{port}")
    except Exception as e:
        return EmailDeliveryResult(
            sent=False,
            via="smtp",
            detail=f"SMTP send failed: {type(e).__name__}: {e}",
        )


# --- Helpers used by the API endpoints --------------------------------------


def find_letter_in_workflow(workflow: dict[str, Any], letter_id: str) -> dict[str, Any] | None:
    for letter in workflow.get("letters", []) or []:
        if letter.get("id") == letter_id:
            return letter
    return None


def letter_meta_from(letter: dict[str, Any], default_sender: str = "Clinical Office") -> LetterMeta:
    return LetterMeta(
        to=letter.get("to") or "Recipient",
        sender=letter.get("from") or default_sender,
        subject=letter.get("subject") or "Pre-Operative Clearance",
        date=letter.get("sentAt"),
    )


def safe_pdf_filename(subject: str) -> str:
    base = subject or "letter"
    cleaned = "".join(c if c.isalnum() or c in (" ", "-", "_") else "_" for c in base)
    return cleaned.strip().replace(" ", "_")[:80] + ".pdf"
